### ISSUE TITLE
name="lookup_unique_idx" in der Doku anpassen

### ISSUE THREAD

**Issue by Dword123** [webfactory/polyglot-bundle#2]
Wenn man den Namen konstant auf "lookup_unique_idx" stellt funktioniert das zwar bei dev und prod, aber bei phpunit-Tests nicht weil die Indizes da eindeutig sein müssen. Vorschläge:
- Das komplett rausnehmen, allerdings geht dann aus der Doku nicht hervor, dass man das name-Feld setzen kann
- Klarmachen, dass man Name auf einen eindeutigen Wert setzen oder weglassen soll

Meinung?

**Comment by MalteWunsch** [comment]
name="..." der Einfachheit halber weg lassen. Ich finde, wir müssen hier nicht Doctrine erklären.

**Comment by Dword123** [comment]
Stimmt eigentlich auch wieder ...
